Repository codesquad-member-2020/sidedish-11, pull requests merged in 2020-04, with the labels that each got.

#5 [BE] 개발환경 설정
  BE/sidedish-11/.gitignore
  BE/sidedish-11/build.gradle
  BE/sidedish-11/gradle/wrapper/gradle-wrapper.jar
  BE/sidedish-11/gradle/wrapper/gradle-wrapper.properties
  BE/sidedish-11/gradlew
  BE/sidedish-11/gradlew.bat
  BE/sidedish-11/settings.gradle
  BE/sidedish-11/src/main/java/dev/codesquad/java/sidedish11/Sidedish11Application.java
  BE/sidedish-11/src/main/resources/application.properties
  BE/sidedish-11/src/test/java/dev/codesquad/java/sidedish11/Sidedish11ApplicationTests.java
Labels: BE

#8 [FE] 개발환경 초기화, 테스트용 header nav component 작성
  FE/.gitignore
  FE/client/.gitignore
  FE/client/README.md
  FE/client/package.json
  FE/client/public/index.html
  FE/client/public/manifest.json
  FE/client/src/App.css
  FE/client/src/App.js
  FE/client/src/components/header/SidedishHeader.js
  FE/client/src/components/header/TopNav.js
  FE/client/src/index.js
  FE/client/src/serviceWorker.js
  FE/client/src/setupProxy.js
  FE/client/yarn.lock
  FE/package.json
  FE/server/.gitignore
  FE/server/package.json
  FE/server/server.js
Labels: FE

#16 [BE] 기본 테이블 생성
  BE/sidedish-11/.gitignore
  BE/sidedish-11/settings.gradle
  BE/sidedish11/.gitignore
  BE/sidedish11/.idea/.gitignore
  BE/sidedish11/.idea/compiler.xml
  BE/sidedish11/.idea/jarRepositories.xml
  BE/sidedish11/.idea/misc.xml
  BE/sidedish11/.idea/vcs.xml
  BE/sidedish11/HELP.md
  BE/sidedish11/build.gradle
  BE/sidedish11/gradle/wrapper/gradle-wrapper.jar
  BE/sidedish11/gradle/wrapper/gradle-wrapper.properties
  BE/sidedish11/gradlew
  BE/sidedish11/gradlew.bat
  BE/sidedish11/settings.gradle
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/Sidedish11Application.java
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/common/CommonUtils.java
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/controller/ApiHomeController.java
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/cors/SimpleCorsFilter.java
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/cors/WebConfig.java
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/entity/Category.java
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/entity/Item.java
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/exception/DataNotFoundException.java
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/exception/ExceptionAdvice.java
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/exception/InvalidTokenException.java
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/exception/UnauthorizedException.java
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/repository/CategoryRepository.java
  BE/sidedish11/src/main/resources/application.properties
  BE/sidedish11/src/main/resources/data.sql
  BE/sidedish11/src/main/resources/schema.sql
  BE/sidedish11/src/test/java/dev/codesquad/java/sidedish11/Sidedish11ApplicationTests.java
Labels: BE

#25 [BE] OAuth 기능 구현
  BE/sidedish11/.gitignore
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/common/CommonUtils.java
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/controller/ApiHomeController.java
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/controller/LoginController.java
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/oauth/Github.java
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/oauth/GithubUser.java
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/oauth/RequestBody.java
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/oauth/RequestHeader.java
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/service/LoginService.java
  BE/sidedish11/src/main/resources/application-secret.properties
  BE/sidedish11/src/main/resources/application.properties
  BE/sidedish11/src/main/resources/schema.sql
  BE/sidedish11/src/main/resources/static/index.html
Labels: BE

#27 [BE] 기본 mock data 입력
  BE/sidedish11/src/main/resources/application.properties
  BE/sidedish11/src/main/resources/data.sql
  BE/sidedish11/src/main/resources/schema.sql
Labels: BE

#28 메인 메뉴 화면 구현
  iOS/Sidedish/.gitmodules
  iOS/Sidedish/Podfile
  iOS/Sidedish/Sidedish.xcodeproj/project.pbxproj
  iOS/Sidedish/Sidedish/Assets.xcassets/LightPurple.colorset/Contents.json
  iOS/Sidedish/Sidedish/Assets.xcassets/OrangeYellow.colorset/Contents.json
  iOS/Sidedish/Sidedish/Assets.xcassets/PointMint.colorset/Contents.json
  iOS/Sidedish/Sidedish/Assets.xcassets/RedOrange.colorset/Contents.json
  iOS/Sidedish/Sidedish/Base.lproj/Main.storyboard
  iOS/Sidedish/Sidedish/Controller/MainViewController.swift
  iOS/Sidedish/Sidedish/Info.plist
  iOS/Sidedish/Sidedish/Model/NetworkManager.swift
  iOS/Sidedish/Sidedish/Model/SidedishInfo.swift
  iOS/Sidedish/Sidedish/Model/SidedishUseCase.swift
  iOS/Sidedish/Sidedish/Utility.swift
  iOS/Sidedish/Sidedish/View/SideDishTableViewCell.swift
  iOS/Sidedish/Sidedish/View/SideDishTableViewCell.xib
  iOS/Sidedish/Sidedish/View/SidedishDataSource.swift
  iOS/Sidedish/Sidedish/View/SidedishTableViewDelegate.swift
  iOS/Sidedish/Sidedish/View/SidedishTableViewHeader.swift
  iOS/Sidedish/Sidedish/View/SidedishTableViewHeader.xib
  iOS/Sidedish/Sidedish/ViewController.swift
Labels: iOS

#29 [FE] 메인 페이지 기능 구현
  FE/client/.gitignore
  FE/client/package.json
  FE/client/src/App.js
  FE/client/src/components/header/SidedishHeader.jsx
  FE/client/src/components/header/menu/MenuNav.jsx
  FE/client/src/components/header/menu/Menus.jsx
  FE/client/src/components/header/menu/MenusSubList.jsx
  FE/client/src/components/header/search/Search.jsx
  FE/client/src/components/header/top/TopNav.jsx
  FE/client/src/components/header/top/TopNavPopup.jsx
  FE/client/src/components/header/top/TopNavPopupSubList.jsx
  FE/client/src/components/main/SidedishMain.jsx
  FE/client/src/components/main/item/Badge.jsx
  FE/client/src/components/main/item/Item.jsx
  FE/client/src/components/main/item/ItemBox.jsx
  FE/client/src/components/main/item/ItemList.jsx
  FE/client/src/components/main/item/SliderArrow.jsx
  FE/client/src/components/main/item/style/Item.css
  FE/client/src/components/main/item/style/SliderArrow.css
  FE/client/src/components/util/useFetch.js
  FE/client/src/globalStyle/App.css
  FE/client/src/globalStyle/reset.css
  FE/client/src/theme.js
Labels: FE

#43 [BE] 데이터 타입 변경
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/dto/ItemDetail.java
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/dto/ItemResponse.java
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/entity/Item.java
  BE/sidedish11/src/main/resources/application.properties
  BE/sidedish11/src/main/resources/data.sql
  BE/sidedish11/src/main/resources/schema.sql
Labels: BE

#45 [BE] DAO 기능 구현
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/controller/ApiMainController.java
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/entity/Badge.java
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/entity/Category.java
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/entity/Color.java
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/entity/DeliveryType.java
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/entity/DetailSection.java
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/entity/Item.java
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/entity/ThumbImage.java
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/repository/CategoryDao.java
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/repository/CategoryRepository.java
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/repository/ItemDao.java
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/repository/ItemRepository.java
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/service/CategoryService.java
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/service/ItemService.java
  BE/sidedish11/src/main/resources/application.properties
  BE/sidedish11/src/main/resources/data.sql
  BE/sidedish11/src/main/resources/schema.sql
  BE/sidedish11/src/test/java/dev/codesquad/java/sidedish11/repository/ItemDaoTest.java
Labels: BE

#49 [BE] OAuth redirect & 상품 여러개 주문 기능 추가
  BE/sidedish11/build.gradle
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/common/CommonUtils.java
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/controller/ApiOrderController.java
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/controller/LoginController.java
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/entity/Item.java
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/service/ItemService.java
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/service/LoginService.java
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/service/OrderService.java
  BE/sidedish11/src/main/resources/application-secret.properties
  BE/sidedish11/src/main/resources/application.properties
  BE/sidedish11/src/main/resources/data.sql
  BE/sidedish11/src/main/resources/static/index.html
Labels: BE

#50 [BE] 뱃지 버그 수정 및 로그인 쿠키 추가
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/common/CommonUtils.java
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/controller/ApiOrderController.java
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/controller/LoginController.java
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/entity/Item.java
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/service/OrderService.java
Labels: BE

#51 [BE] sql 데이터 추가
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/common/CommonUtils.java
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/controller/LoginController.java
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/service/OrderService.java
  BE/sidedish11/src/main/resources/application.properties
  BE/sidedish11/src/main/resources/data.sql
Labels: BE

#52 [FE] 메인 페이지 구현
  FE/client/.gitignore
  FE/client/build/asset-manifest.json
  FE/client/build/index.html
  FE/client/build/precache-manifest.5b5d7b72a1aa943bf62f191c810e8dd4.js
  FE/client/build/service-worker.js
  FE/client/build/static/css/main.f25d2e91.chunk.css
  FE/client/build/static/css/main.f25d2e91.chunk.css.map
  FE/client/build/static/js/2.5bd6019c.chunk.js
  FE/client/build/static/js/2.5bd6019c.chunk.js.LICENSE.txt
  FE/client/build/static/js/2.5bd6019c.chunk.js.map
  FE/client/build/static/js/main.0aefb7ec.chunk.js
  FE/client/build/static/js/main.0aefb7ec.chunk.js.map
  FE/client/build/static/js/runtime-main.784c586e.js
  FE/client/build/static/js/runtime-main.784c586e.js.map
  FE/client/src/components/header/top/TopNav.jsx
  FE/client/src/components/main/SidedishMain.jsx
  FE/client/src/components/main/item/Badge.jsx
  FE/client/src/components/main/item/Item.jsx
  FE/client/src/components/main/item/ItemBox.jsx
  FE/client/src/components/main/item/ItemList.jsx
  FE/client/src/components/main/item/SliderArrow.jsx
  FE/client/src/components/main/item/detail/DetailImage.jsx
  FE/client/src/components/main/item/detail/DetailInfo.jsx
  FE/client/src/components/main/item/detail/DetailInfoCount.jsx
  FE/client/src/components/main/item/detail/DetailInfoStatic.jsx
  FE/client/src/components/main/item/detail/DetailPurchaseButton.jsx
  FE/client/src/components/main/item/detail/ItemDetail.jsx
  FE/client/src/components/main/item/detail/ThumbImages.jsx
  FE/client/src/components/main/item/detail/style/DetailInfo.css
  FE/client/src/components/main/item/style/Item.css
  FE/client/src/components/main/item/style/SliderArrow.css
  FE/client/src/constants/url.js
  FE/client/src/util/cookie.js
  FE/client/src/util/useFetch.js
Labels: FE

#55 [BE] tomcat 설치 후 war 배포
  BE/sidedish11/build.gradle
  BE/sidedish11/src/main/java/dev/codesquad/java/sidedish11/Sidedish11Application.java
Labels: BE
